
noun1 = input("noun -")
state = input("any state -")
verb_not_ending_in_ing = input("verb not ending in -ing -")
noun2 = input("noun -")
adjective1 = input("adjective -")
noun3 = input("noun -")
verb1 = input("verb -")
verb_ending_with_ing = input("verb ending with -ing -")
plural_noun = input("plural noun -")
noun4 = input("noun -")
noun5 = input("noun -")
print()
print("I am %s and I want to run for president." % (noun1))
print("%s is very important to me and I want to %s it to help make it better." % (state, verb_not_ending_in_ing))
print("I always keep %s, I’m %s, and I am always looking out for the well being of our %s." % (noun2, adjective1, noun3))
print("I love to %s with others, it is always important to get points across." % (verb1))
print("I enjoy %s and president definitely takes it’s part in that." % (verb_ending_with_ing))
print("I will make sure that the money is spent in places that are highly requested among the %s to make %s better." % (plural_noun, noun4))
print("I think being president is the right job for me. Bank on your vote, %s for president!" % (noun5))
